//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication5.QStatus {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="QStatus.QuotationStatusSoap")]
    public interface QuotationStatusSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddQuotationStatus", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool AddQuotationStatus(int statusId, string sName, string pName, int total, string status);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddQuotationStatus", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> AddQuotationStatusAsync(int statusId, string sName, string pName, int total, string status);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ViewAllQStatus", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable ViewAllQStatus();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ViewAllQStatus", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> ViewAllQStatusAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateQuotationStatus", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool UpdateQuotationStatus(int statusId, string sName, string pName, int total, string status);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateQuotationStatus", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> UpdateQuotationStatusAsync(int statusId, string sName, string pName, int total, string status);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface QuotationStatusSoapChannel : WebApplication5.QStatus.QuotationStatusSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class QuotationStatusSoapClient : System.ServiceModel.ClientBase<WebApplication5.QStatus.QuotationStatusSoap>, WebApplication5.QStatus.QuotationStatusSoap {
        
        public QuotationStatusSoapClient() {
        }
        
        public QuotationStatusSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public QuotationStatusSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public QuotationStatusSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public QuotationStatusSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool AddQuotationStatus(int statusId, string sName, string pName, int total, string status) {
            return base.Channel.AddQuotationStatus(statusId, sName, pName, total, status);
        }
        
        public System.Threading.Tasks.Task<bool> AddQuotationStatusAsync(int statusId, string sName, string pName, int total, string status) {
            return base.Channel.AddQuotationStatusAsync(statusId, sName, pName, total, status);
        }
        
        public System.Data.DataTable ViewAllQStatus() {
            return base.Channel.ViewAllQStatus();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> ViewAllQStatusAsync() {
            return base.Channel.ViewAllQStatusAsync();
        }
        
        public bool UpdateQuotationStatus(int statusId, string sName, string pName, int total, string status) {
            return base.Channel.UpdateQuotationStatus(statusId, sName, pName, total, status);
        }
        
        public System.Threading.Tasks.Task<bool> UpdateQuotationStatusAsync(int statusId, string sName, string pName, int total, string status) {
            return base.Channel.UpdateQuotationStatusAsync(statusId, sName, pName, total, status);
        }
    }
}
